create new branch

diff --git a/.github/workflows/bundle-schema.yml b/.github/workflows/bundle-schema.yml
--- a/.github/workflows/bundle-schema.yml
+++ b/.github/workflows/bundle-schema.yml
@@ -14,6 +14,14 @@ jobs:
     steps:
       - name: Check out repository code
         uses: actions/checkout@v3
+      - name: Create new branch
+        shell: bash
+        run: |
+          git config --global user.name github-actions[bot]
+          git config --global user.email github-actions[bot]@users.noreply.github.com
+          git checkout -b ci/update-schemas
+          git push -u origin ci/update-schemas
+          git checkout main
       - name: Bundle & Push JSON schema for application schemas
         uses: ./.github/actions/bundle-schema
         with:
@@ -29,3 +37,23 @@ jobs:
         with:
           schema-path: ./schemas/controller-descriptions/schema/controller.schema.json
           schema: controller.schema.json
+      - name: Create pull request
+        steps:
+          - uses: actions/checkout@v3
+            with:
+              ref: ci/update-schemas
+          - name: Create pull request
+            shell: bash
+            run: |
+              MESSAGE=$(
+                gh pr create \
+                -B develop \
+                -H ci/update-schemas \
+                --title 'Update schemas' \
+                --body 'This PR was automatically created by GitHub actions in response to schema changes. Please review and update any impacted code before merging the changes.' \
+                --reviewer jjenscodee \
+                2>&1
+              ) || echo "::warning::Error creating the PR: $MESSAGE"
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
